/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type BindProtocol = ("http" | "tls" | "tcp") | "auto";
export type TunnelProtocol = "direct" | "hboneWaypoint" | "hboneGateway" | "proxy" | "connect";
export type ListenerProtocol =
  | "HBONE"
  | "HTTP"
  | {
      HTTPS: ServerTLSConfig;
    }
  | {
      TLS: ServerTLSConfig;
    }
  | "TCP";
export type ServerTLSConfig = null;
export type HeaderValueMatch =
  | "invalid"
  | {
      exact: string;
    }
  | {
      regex: string;
    };
export type QueryValueMatch =
  | "invalid"
  | {
      exact: string;
    }
  | {
      regex: string;
    };
export type RouteBackendReference = {
  weight: number;
  inlinePolicies?: unknown[];
  [k: string]: unknown;
} & RouteBackendReference1;
export type RouteBackendReference1 =
  | {
      service: {
        name: NamespacedHostname;
        port: number;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      backend: string;
      [k: string]: unknown;
    }
  | {
      routeGroup: string;
      [k: string]: unknown;
    }
  | {
      invalid: null;
      [k: string]: unknown;
    };
export type SimpleLocalBackend =
  | {
      service: {
        name: NamespacedHostname;
        port: number;
      };
    }
  | {
      /**
       * Hostname or IP address
       */
      host: string;
    }
  | {
      /**
       * Explicit backend reference. Backend must be defined in the top level backends list
       */
      backend: string;
    };

export interface StoresDump {
  workloads: unknown[];
  services: unknown[];
  binds: DumpBind[];
  routes: RoutesDump;
  policies: unknown[];
  backends: unknown[];
  [k: string]: unknown;
}
export interface DumpBind {
  key: string;
  address: string;
  protocol: BindProtocol;
  tunnelProtocol: TunnelProtocol;
  listeners: {
    [k: string]: DumpListener;
  };
  [k: string]: unknown;
}
export interface DumpListener {
  key: string;
  gatewayName: string;
  gatewayNamespace: string;
  listenerName: string;
  listenerSet?: ResourceName | null;
  /**
   * Can be a wildcard
   */
  hostname: string;
  protocol: ListenerProtocol;
  routes?: {
    [k: string]: Route;
  } | null;
  tcpRoutes?: {
    [k: string]: TCPRoute;
  } | null;
  [k: string]: unknown;
}
export interface ResourceName {
  name: string;
  namespace: string;
}
export interface Route {
  key: string;
  /**
   * Service this route targets (set when parentRef is a Service).
   */
  serviceKey?: NamespacedHostname | null;
  /**
   * Port of the targeted service this route is scoped to. Zero matches any port.
   */
  servicePort?: number;
  name: string;
  namespace: string;
  ruleName?: string | null;
  kind?: string | null;
  /**
   * Can be a wildcard
   */
  hostnames?: string[];
  matches?: RouteMatch[];
  backends?: RouteBackendReference[];
  llmRouter?: {
    [k: string]: unknown;
  };
  inlinePolicies?: unknown[];
  [k: string]: unknown;
}
export interface NamespacedHostname {
  namespace: string;
  hostname: string;
  [k: string]: unknown;
}
export interface RouteMatch {
  headers?: HeaderMatch[];
  path:
    | "invalid"
    | {
        exact: string;
      }
    | {
        pathPrefix: string;
      }
    | {
        regex: string;
      };
  method?: string;
  query?: QueryMatch[];
}
export interface HeaderMatch {
  name: string;
  value: HeaderValueMatch;
}
export interface QueryMatch {
  name: string;
  value: QueryValueMatch;
}
export interface TCPRoute {
  key: string;
  /**
   * Service this route targets (set when parentRef is a Service).
   */
  serviceKey?: NamespacedHostname | null;
  /**
   * Port of the targeted service this route is scoped to. Zero matches any port.
   */
  servicePort?: number;
  name: string;
  namespace: string;
  ruleName?: string | null;
  kind?: string | null;
  hostnames?: string[];
  backends?: TCPRouteBackendReference[];
  [k: string]: unknown;
}
export interface TCPRouteBackendReference {
  weight: number;
  backend: SimpleLocalBackend;
  inlinePolicies?: unknown[];
  [k: string]: unknown;
}
export interface RoutesDump {
  httpMesh: {
    [k: string]: {
      [k: string]: Route;
    };
  };
  tcpMesh: {
    [k: string]: {
      [k: string]: TCPRoute;
    };
  };
  routeGroups: {
    [k: string]: {
      [k: string]: Route;
    };
  };
  [k: string]: unknown;
}
